services:
  - type: web
    name: equilibragem-be
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    postDeploy:
      - bundle exec rails db:migrate
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: SOLID_QUEUE_IN_PUMA
        value: "1"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: equilibragem-be-db
          property: connectionString
      - key: CACHE_DATABASE_URL
        fromDatabase:
          name: equilibragem-be-db
          property: connectionString
      - key: QUEUE_DATABASE_URL
        fromDatabase:
          name: equilibragem-be-db
          property: connectionString
      - key: CABLE_DATABASE_URL
        fromDatabase:
          name: equilibragem-be-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: equilibragem-redis
          property: connectionString
  - type: redis
    name: equilibragem-redis
    plan: starter
databases:
  - name: equilibragem-be-db
    plan: starter
